# Generated by Django 3.2.8 on 2021-10-13 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackernews', '0002_auto_20211014_0019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newspost',
            name='text',
            field=models.CharField(blank=True, max_length=2500),
        ),
    ]
